server:
  port: 3300
  # Heart beat - 1m, 4h and etc
  update_interval: 31m
  # Target to download
  download_dir: download
  # Upload catalog from remote clients
  upload_dir: upload
  # Web server public catalog
  public_dir: public
  # Disable download lists (TODO)
  disable_download: True
  # Ping interval (TODO)
  ping_interval: 5m
  # Ping timeout (TODO)
  ping_timeout: 2s

# Target hosts for ping
# IP or DN with port
ping:
  - host:
      name: 1.1.1.1
      port: 443
  - host:
      name: 9.9.9.9
      port: 53
  - host:
      name: bld.sys-adm.in
      port: 53
  - host:
      name: bld.sys-adm.in
      port: 443
  - host:
      name: a-bld.sys-adm.in
      port: 53
  - host:
      name: a-bld.sys-adm.in
      port: 443

lists:
  bl:
    # - TODO: Download files with same names?
    - https://raw.githubusercontent.com/m0zgen/dns-hole/master/dns-blacklist.txt
    - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Spam/hosts
  bl_plain:
    - https://raw.githubusercontent.com/m0zgen/bld-agregator/data/blocklist.txt
    - https://raw.githubusercontent.com/m0zgen/dns-hole/master/regex/common-bl.txt
  wl:
    - https://raw.githubusercontent.com/m0zgen/dns-hole/master/whitelist.txt
    - https://raw.githubusercontent.com/m0zgen/dns-hole/master/vendors-wl/microsoft.txt
    - https://raw.githubusercontent.com/m0zgen/dns-hole/master/vendors-wl/google.txt
  wl_plain:
    - https://raw.githubusercontent.com/m0zgen/dns-hole/master/regex/common-wl.txt
    - https://raw.githubusercontent.com/m0zgen/dns-hole/master/bld-testing/wl-testing
  ip_plain:
    - https://osint.digitalside.it/Threat-Intel/lists/latestips.txt
    - https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/firehol_level2.netset
    - https://feodotracker.abuse.ch/downloads/ipblocklist_recommended.txt
    - https://iplists.firehol.org/files/firehol_level1.netset
    - https://raw.githubusercontent.com/stamparm/ipsum/master/levels/2.txt

