name: Cactusd-Agro
on:
  push:
    branches:
      - dev
  schedule:
    # every 12 hours
    - cron: "0 */12 * * *"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          # checkout all branches
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          sudo python3 -m pip install pybadges

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: Install Go dependencies
        run: |
          go version
          go install

      - name: Build
        run: go build -o cactusd -v .

      - name: Generate lists
        run: |
          sudo ./cactusd -generate
          sudo python3 addits/badges.py
          sudo cp -rf public/files/*.svg /tmp
          sudo cp -rf public/files/*.txt /tmp

      - name: Remove remote data branch
        if: ${{ success() }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git push origin :data

      - name: Checkout
        if: ${{ success() }}
        run: |
          git checkout --orphan data
          git rm -rf .
          sudo rm -rf download merged public upload cactusd
          cp -rf /tmp/*.txt .
          cp -rf /tmp/*.svg .

      - name: Add files
        if: ${{ success() }}
        run: |
          git add .

      - name: Commit Push
        if: ${{ success() }}
        run: |
          git commit -m "blocklist generated"
          git push origin data