name: Cactusd-Agro
on:
  push:
    branches:
      - dev
  schedule:
    # At the end of every day
    # - cron: "0 0 * * *"
    # Con every 12 hours
    - cron: "0 */12 * * *"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          # checkout all branches
          fetch-depth: 0

      - name: Set up Go
          uses: actions/setup-go@v4
          with:
            go-version: 1.20

      - name: Build
          run: go build -o cactusd -v ./...

      - name: Generate lists
        run: |
          sudo ./cactusd -generate
          sudo cp -rf public/files/*.txt /tmp

      - name: Remove remote data branch
        if: ${{ success() }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git push origin :data

      - name: Checkout
        if: ${{ success() }}
        run: |
          git checkout --orphan data
          git rm -rf .
          cp -rf /tmp/*.txt .

      - name: Add files
        if: ${{ success() }}
        run: |
          git add .

      - name: Commit Push
        if: ${{ success() }}
        run: |
          git commit -m "blocklist generated"
          git push origin data